Rework Select Sonar
OSOceanAcoustics/echoregions pull request #169
Opened 2024-01-09 21:16 UTC by ctuguinay

The primary change is that the function now uses dataset/data array time variable start and end selection instead of filename time values.

2024-01-09 21:38 UTC, ctuguinay commented
@leewujung This is ready to be reviewed

2024-01-10 00:16 UTC, ctuguinay commented
Codecov says 'All modified and coverable lines are covered by tests ✅', so I think this coverage difference is alright?

2024-03-09 00:43 UTC, leewujung requested changes
Hey @ctuguinay : Thanks for the PR. Sorry it took a while to get to this. 

The modifications to the function looks great. The only thing I would suggest is to add a test to test for actually "gating" out the wrong Sv datasets/dataarrays completely outside of the regions start/end times.

The current test contains 1 dataset loaded from file and 1 empty dataset. How about constructing a few tiny datasets with just a few time points, and check if the right datasets are selected?

2024-03-12 22:49 UTC, ctuguinay commented
Hey @leewujung, I added a few more checks for the gating in the `test_select_sonar` function. Do you think I should remove the `parse_simrad_fname_time` function from `utils/time.py`? The only place it was used was in the previous iteration of `select_sonar`.

2024-03-12 23:39 UTC, leewujung commented
Yeah, I think that function could be removed.

2024-03-13 00:20 UTC, ctuguinay commented
@leewujung Just removed it

2024-03-13 00:32 UTC, leewujung commented on echoregions/tests/test_regions2d.py
> +    Tests select_sonar.
Maybe here these should be `select_sonar_file` to be consistent with the function name?

2024-03-13 00:40 UTC, leewujung approved these changes
Looks good! I only had a small comment of test function name. Feel free to merge after that.

2024-03-13 04:20 UTC, leewujung commented
@ctuguinay : I pulled in all changes from `main`.

2024-03-13 18:10 UTC, merged